name = "radio-epg"
main = "src/index.ts"
compatibility_date = "2026-07-13"

[vars]
CORS_ORIGINS = "https://radio.bsod.kr,https://mysna.github.io,http://localhost:8000"

[[d1_databases]]
binding = "DB"
database_name = "radio-epg"
database_id = "851a1f51-1757-4684-be24-5610c3e5fa4e"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "radio-epg-images"
